name: nodeapp-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push nodeapp to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Execute remote SSH commands using key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            ls
            cd nodesample
            npm install
            pm2 start npm --name "nodeapp" -- start
            pm2 save
            pm2 status
            echo "Deployment completed successfully"